<a href="https://colab.research.google.com/github/mauricioamq/nlp/blob/main/Lab_Bag_of_Words%2C_TFIDF%2C_Document_Similarity_Students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 6**
Mauricio Martinez
##Miami Dade College
##CAI3303C-2267-13181|Natural Language Processing
Prof. George Gabb

October, 2026

# Lab - Bag of Words, TFIDF, Document Similarity

## Lab Summary:

In this lab we will be learning about document similarity and word embeddings.
## Lab Goal:
Upon completion of this lab, the student should be able to:
<ul>
    <li> understand cosine, jaccard, and Euclidean similarity </li>
    <li> test if 2 documents are similar or not </li>
</ul>


## Time Requried:
This lab should take 4 hours to complete for those unfamiliar with the tools.
Hint: The lab flow is already prepared for you, just read through the links and try implementing them. Don't try to have it all figured out before starting.

## Lab Preparation:
<ul>
    <li> Review Lecture for Week 5 and 6 </li>
</ul>

## Hardware Needed:
Any computer with access to the internet and web browser



## Import Packages and Classes (Initial)

In this lab we will be using the following libraries:
<ol>
    <li> NLTK </li>
    <li> Pandas </li>
    <li> Matplotlib </li>
    <li> Gensim </li>
</ol>


<b>Matplotlib</b> Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It is completely free and open source.

![Image](https://miro.medium.com/max/1050/1*EsqDYFK-IzGEAm4FyZP0wQ.jpeg)

More here: https://matplotlib.org/stable/index.

<b>Pandas</b> is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

![Image](https://miro.medium.com/max/819/1*Dss7A8Z-M4x8LD9ccgw7pQ.png)

More here: https://pandas.pydata.org/

<b>Gensim</b> supports a variety of other NLP tasks such as:
- converting words to vectors (word2vec),
- document to vectors (doc2vec),
- finding text similarity, and text summarization

![Gensim](https://repository-images.githubusercontent.com/1349775/202c4680-8f7c-11e9-91c6-745fdcbeffe8)

More about Gensim here:
https://pypi.org/project/gensim/

<b>Bag of Words</b> is a Natural Language Processing technique of text modelling. A bag of words is a representation of text that describes the occurrence of words within a document.

At first, we would see how to find the bag of words representation without using any library. Then, we would use sklearn library to achieve the same thing.

In [10]:
def vectorize(tokens):
    ''' This function returns the bag of words representation. You need to use this function ahead'''
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
        #tokens.count(w) tells us the count of each word in the filtered_vocab in tokens
        #filtered_vocab contains list of unique words after filtering stopwords and punctuation
    return vector


def unique(sequence):
    '''this function returns the vocabulary of words'''
    seen = set()
    return set(sequence)

In [11]:
from os.path import split
stopwords=["to","is","a","the","of"]
special_char=[",",":"," ",";",".","?"]

#your list of sentences
string1="Paris is the capital of France"
string2="Milan is the fashion capital of the world"

#convert them to lower case
#your code here
string1=string1.lower()
string2=string2.lower()

#your code here
#split the sentences into tokens
tokens1=string1.split()
tokens2=string2.split()

print(tokens1)
print(tokens2)

['paris', 'is', 'the', 'capital', 'of', 'france']
['milan', 'is', 'the', 'fashion', 'capital', 'of', 'the', 'world']

Now, we will find the vocabulary which is the set of unique words in the corpus. We also need to filter it since we do not want stopwords or special characters to influence our vocabulary.

In [12]:
vocab=unique(tokens1+tokens2)
vocab

{'capital', 'fashion', 'france', 'is', 'milan', 'of', 'paris', 'the', 'world'}

In [13]:
filtered_vocab=[]
#filtered_vocab should contain the words from vocab that are not stopwords or special_char
#your code here
filtered_vocab=[word for word in vocab if word not in stopwords and word not in special_char]
filtered_vocab

['world', 'milan', 'capital', 'paris', 'france', 'fashion']

In [14]:
print(filtered_vocab)
#convert sentences into vectords
vector1=vectorize(tokens1)
print(vector1)
vector2=vectorize(tokens2)
print(vector2)

['world', 'milan', 'capital', 'paris', 'france', 'fashion']
[0, 0, 1, 1, 1, 0]
[1, 1, 1, 0, 0, 1]

Well, that was the bag of words, the hard way! Now, we would do the same using the sklearn library

In [15]:
text= "Sweden is part of the geographical area of Fennoscandia. The climate is in general mild for its northerly latitude due to significant maritime influence. In spite of the high latitude, Sweden often has warm continental summers, being located in between the North Atlantic, the Baltic Sea, and vast Russia. The general climate and environment vary significantly from the south and north due to the vast latitudal difference, and much of Sweden has reliably cold and snowy winters. Southern Sweden is predominantly agricultural, while the north is heavily forested and includes a portion of the Scandinavian Mountains."
#Split text into sentences. Store the sentences into a list
#Your code here:
list1=text.split('.')
list1

['Sweden is part of the geographical area of Fennoscandia',
 ' The climate is in general mild for its northerly latitude due to significant maritime influence',
 ' In spite of the high latitude, Sweden often has warm continental summers, being located in between the North Atlantic, the Baltic Sea, and vast Russia',
 ' The general climate and environment vary significantly from the south and north due to the vast latitudal difference, and much of Sweden has reliably cold and snowy winters',
 ' Southern Sweden is predominantly agricultural, while the north is heavily forested and includes a portion of the Scandinavian Mountains',
 '']

We would use the sklearn library to find bag of word representation automatically.

The CountVectorizer provides a simple way to both tokenize a collection of text documents and build a vocabulary of known words, but also to encode new documents using that vocabulary.

You can use it as follows:

- Create an instance of the CountVectorizer class.
- Call the fit() function in order to learn a vocabulary from one or more documents.
- Call the transform() function on one or more documents as needed to encode each as a vector.

More about this here: https://machinelearningmastery.com/prepare-text-data-machine-learning-scikit-learn

In [16]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

#your code here
cv = CountVectorizer(ngram_range=(1,1))
cv.fit_transform(list1)
pd.DataFrame(cv.fit_transform(list1).toarray(),columns=cv.get_feature_names_out())

,agricultural,and,area,atlantic,baltic,being,between,climate,cold,continental,difference,due,environment,fennoscandia,for,forested,from,general,geographical,has,heavily,high,in,includes,influence,is,its,latitudal,latitude,located,maritime,mild,mountains,much,north,northerly,of,often,part,portion,predominantly,reliably,russia,scandinavian,sea,significant,significantly,snowy,south,southern,spite,summers,sweden,the,to,vary,vast,warm,while,winters
0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,1,1,1,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0
2,0,1,0,1,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,2,0,0,0,0,0,1,1,0,0,0,0,1,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,1,1,1,3,0,0,1,1,0,0
3,0,4,0,0,0,0,0,1,1,0,1,1,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,1,3,1,1,1,0,0,1
4,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,2,0,0,0,0,0,0,1,0,1,0,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,1,2,0,0,0,0,1,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [17]:
import pandas as pd

# Configure pandas to wrap wide DataFrames across multiple lines
pd.set_option('display.width', 80)          # Set limit for line width
pd.set_option('display.expand_frame_repr', True)  # Split/wrap columns onto new lines
pd.set_option('display.max_columns', None)        # Show all columns without truncation

# Let's print the DataFrame again to see the wrapped format
print(pd.DataFrame(cv.fit_transform(list1).toarray(), columns=cv.get_feature_names_out()))

   agricultural  and  area  atlantic  baltic  being  between  climate  cold  \
0             0    0     1         0       0      0        0        0     0
1             0    0     0         0       0      0        0        1     0
2             0    1     0         1       1      1        1        0     0
3             0    4     0         0       0      0        0        1     1
4             1    1     0         0       0      0        0        0     0
5             0    0     0         0       0      0        0        0     0

   continental  difference  due  environment  fennoscandia  for  forested  \
0            0           0    0            0             1    0         0
1            0           0    1            0             0    1         0
2            1           0    0            0             0    0         0
3            0           1    1            1             0    0         0
4            0           0    0            0             0    0         1
5            0           0    0            0             0    0         0

   from  general  geographical  has  heavily  high  in  includes  influence  \
0     0        0             1    0        0     0   0         0          0
1     0        1             0    0        0     0   1         0          1
2     0        0             0    1        0     1   2         0          0
3     1        1             0    1        0     0   0         0          0
4     0        0             0    0        1     0   0         1          0
5     0        0             0    0        0     0   0         0          0

   is  its  latitudal  latitude  located  maritime  mild  mountains  much  \
0   1    0          0         0        0         0     0          0     0
1   1    1          0         1        0         1     1          0     0
2   0    0          0         1        1         0     0          0     0
3   0    0          1         0        0         0     0          0     1
4   2    0          0         0        0         0     0          1     0
5   0    0          0         0        0         0     0          0     0

   north  northerly  of  often  part  portion  predominantly  reliably  \
0      0          0   2      0     1        0              0         0
1      0          1   0      0     0        0              0         0
2      1          0   1      1     0        0              0         0
3      1          0   1      0     0        0              0         1
4      1          0   1      0     0        1              1         0
5      0          0   0      0     0        0              0         0

   russia  scandinavian  sea  significant  significantly  snowy  south  \
0       0             0    0            0              0      0      0
1       0             0    0            1              0      0      0
2       1             0    1            0              0      0      0
3       0             0    0            0              1      1      1
4       0             1    0            0              0      0      0
5       0             0    0            0              0      0      0

   southern  spite  summers  sweden  the  to  vary  vast  warm  while  winters
0         0      0        0       1    1   0     0     0     0      0        0
1         0      0        0       0    1   1     0     0     0      0        0
2         0      1        1       1    3   0     0     1     1      0        0
3         0      0        0       1    3   1     1     1     0      0        1
4         1      0        0       1    2   0     0     0     0      1        0
5         0      0        0       0    0   0     0     0     0      0        0

The next task is to find the bag of words representation again but this time, do it for <b>bigrams</b>!

A bigram or digram is a sequence of two adjacent elements from a string of tokens, which are typically letters, syllables, or words. A bigram is an n-gram for n=2.

In [18]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

#your code here
cv = CountVectorizer(ngram_range=(2,2))
cv.fit_transform(list1)

print(pd.DataFrame(cv.fit_transform(list1).toarray(),columns=cv.get_feature_names_out()))

   agricultural while  and environment  and includes  and much  and north  \
0                   0                0             0         0          0
1                   0                0             0         0          0
2                   0                0             0         0          0
3                   0                1             0         1          1
4                   1                0             1         0          0
5                   0                0             0         0          0

   and snowy  and vast  area of  atlantic the  baltic sea  being located  \
0          0         0        1             0           0              0
1          0         0        0             0           0              0
2          0         1        0             1           1              1
3          1         0        0             0           0              0
4          0         0        0             0           0              0
5          0         0        0             0           0              0

   between the  climate and  climate is  cold and  continental summers  \
0            0            0           0         0                    0
1            0            0           1         0                    0
2            1            0           0         0                    1
3            0            1           0         1                    0
4            0            0           0         0                    0
5            0            0           0         0                    0

   difference and  due to  environment vary  for its  forested and  from the  \
0               0       0                 0        0             0         0
1               0       1                 0        1             0         0
2               0       0                 0        0             0         0
3               1       1                 1        0             0         1
4               0       0                 0        0             1         0
5               0       0                 0        0             0         0

   general climate  general mild  geographical area  has reliably  has warm  \
0                0             0                  1             0         0
1                0             1                  0             0         0
2                0             0                  0             0         1
3                1             0                  0             1         0
4                0             0                  0             0         0
5                0             0                  0             0         0

   heavily forested  high latitude  in between  in general  in spite  \
0                 0              0           0           0         0
1                 0              0           0           1         0
2                 0              1           1           0         1
3                 0              0           0           0         0
4                 1              0           0           0         0
5                 0              0           0           0         0

   includes portion  is heavily  is in  is part  is predominantly  \
0                 0           0      0        1                 0
1                 0           0      1        0                 0
2                 0           0      0        0                 0
3                 0           0      0        0                 0
4                 1           1      0        0                 1
5                 0           0      0        0                 0

   its northerly  latitudal difference  latitude due  latitude sweden  \
0              0                     0             0                0
1              1                     0             1                0
2              0                     0             0                1
3              0                     1             0                0
4              0                     0             0                0
5              0                     0             0                0

   located in  maritime influence  mild for  much of  north atlantic  \
0           0                   0         0        0               0
1           0                   1         1        0               0
2           1                   0         0        0               1
3           0                   0         0        1               0
4           0                   0         0        0               0
5           0                   0         0        0               0

   north due  north is  northerly latitude  of fennoscandia  of sweden  \
0          0         0                   0                1          0
1          0         0                   1                0          0
2          0         0                   0                0          0
3          1         0                   0                0          1
4          0         1                   0                0          0
5          0         0                   0                0          0

   of the  often has  part of  portion of  predominantly agricultural  \
0       1          0        1           0                           0
1       0          0        0           0                           0
2       1          1        0           0                           0
3       0          0        0           0                           0
4       1          0        0           1                           1
5       0          0        0           0                           0

   reliably cold  scandinavian mountains  sea and  significant maritime  \
0              0                       0        0                     0
1              0                       0        0                     1
2              0                       0        1                     0
3              1                       0        0                     0
4              0                       1        0                     0
5              0                       0        0                     0

   significantly from  snowy winters  south and  southern sweden  spite of  \
0                   0              0          0                0         0
1                   0              0          0                0         0
2                   0              0          0                0         1
3                   1              1          1                0         0
4                   0              0          0                1         0
5                   0              0          0                0         0

   summers being  sweden has  sweden is  sweden often  the baltic  \
0              0           0          1             0           0
1              0           0          0             0           0
2              1           0          0             1           1
3              0           1          0             0           0
4              0           0          1             0           0
5              0           0          0             0           0

   the climate  the general  the geographical  the high  the north  \
0            0            0                 1         0          0
1            1            0                 0         0          0
2            0            0                 0         1          1
3            0            1                 0         0          0
4            0            0                 0         0          1
5            0            0                 0         0          0

   the scandinavian  the south  the vast  to significant  to the  \
0                 0          0         0               0       0
1                 0          0         0               1       0
2                 0          0         0               0       0
3                 0          1         1               0       1
4                 1          0         0               0       0
5                 0          0         0               0       0

   vary significantly  vast latitudal  vast russia  warm continental  \
0                   0               0            0                 0
1                   0               0            0                 0
2                   0               0            1                 1
3                   1               1            0                 0
4                   0               0            0                 0
5                   0               0            0                 0

   while the
0          0
1          0
2          0
3          0
4          1
5          0

<b>TFIDF</b>

Term frequency–inverse document frequency, is a numerical statistic that is intended to reflect how important a word is to a document in a collection or corpus

![Image](https://miro.medium.com/max/3604/1*qQgnyPLDIkUmeZKN2_ZWbQ.png)

You can read more about TFIDF  here: http://www.tfidf.com/, https://programminghistorian.org/en/lessons/analyzing-documents-with-tfidf

Now, let's implement tfidf first without libraries and then with them!

In [19]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

For this section we would be working with three documents:

In [20]:
doc1 = 'When does summer begin , When'
doc2 = 'The rain soothes my soul'
doc3 = 'The winter is lovely but long'

Our corpus here is three documents: doc1, doc2, and doc3

In [21]:
#split each of the three documents into tokens. Store the tokens from doc1 in a variable bowDOC1
#Store the tokens from doc2 in a variable bowDOC2. Store the tokens from doc3 in a variable bowDOC3
#your code here
bowDOC1=doc1.split()
bowDOC2=doc2.split()
bowDOC3=doc3.split()
print(bowDOC1)
print(bowDOC2)
print(bowDOC3)

['When', 'does', 'summer', 'begin', ',', 'When']
['The', 'rain', 'soothes', 'my', 'soul']
['The', 'winter', 'is', 'lovely', 'but', 'long']

In [22]:
#Remember the vocabulary is the set of unique words from all the documents
#find the vocabulary by finding the unique words of bowDOC1, bowDOC2, and bowDOC3
#your code here
vocabulary=unique(bowDOC1+bowDOC2+bowDOC3)
vocabulary

{',',
 'The',
 'When',
 'begin',
 'but',
 'does',
 'is',
 'long',
 'lovely',
 'my',
 'rain',
 'soothes',
 'soul',
 'summer',
 'winter'}

Now, we have the vocabulary- the set of unique words. We need to convert our documents into vectors so that we can pass these vectors on to our machines for any sort of computation.

In [23]:
#finding the bow vector for doc1
vectorA = dict.fromkeys(vocabulary, 0)
print(vectorA)
for word in bowDOC1:
    vectorA[word] += 1
print(vectorA)

{'soothes': 0, 'is': 0, 'rain': 0, 'When': 0, 'begin': 0, 'winter': 0, 'does': 0, 'long': 0, 'but': 0, ',': 0, 'summer': 0, 'soul': 0, 'lovely': 0, 'The': 0, 'my': 0}
{'soothes': 0, 'is': 0, 'rain': 0, 'When': 2, 'begin': 1, 'winter': 0, 'does': 1, 'long': 0, 'but': 0, ',': 1, 'summer': 1, 'soul': 0, 'lovely': 0, 'The': 0, 'my': 0}

In [24]:
#find the bow vector for doc2
#your code here
vectorB = dict.fromkeys(vocabulary, 0)
print(vectorB)
for word in bowDOC2:
    vectorB[word] += 1
print(vectorB)

{'soothes': 0, 'is': 0, 'rain': 0, 'When': 0, 'begin': 0, 'winter': 0, 'does': 0, 'long': 0, 'but': 0, ',': 0, 'summer': 0, 'soul': 0, 'lovely': 0, 'The': 0, 'my': 0}
{'soothes': 1, 'is': 0, 'rain': 1, 'When': 0, 'begin': 0, 'winter': 0, 'does': 0, 'long': 0, 'but': 0, ',': 0, 'summer': 0, 'soul': 1, 'lovely': 0, 'The': 1, 'my': 1}

In [25]:
#find the bow vector for doc3
#your code here
vectorC = dict.fromkeys(vocabulary, 0)
print(vectorC)
for word in bowDOC3:
    vectorC[word] += 1
print(vectorC)

{'soothes': 0, 'is': 0, 'rain': 0, 'When': 0, 'begin': 0, 'winter': 0, 'does': 0, 'long': 0, 'but': 0, ',': 0, 'summer': 0, 'soul': 0, 'lovely': 0, 'The': 0, 'my': 0}
{'soothes': 0, 'is': 1, 'rain': 0, 'When': 0, 'begin': 0, 'winter': 1, 'does': 0, 'long': 1, 'but': 1, ',': 0, 'summer': 0, 'soul': 0, 'lovely': 1, 'The': 1, 'my': 0}

TFIDF consists of 2 steps: finding the TF and the IDF. The final result is just the product of TF and IDF.

In [26]:
#this is a function for computing term frequency
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)#finds the length of list bagOfWords
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount) #finding term frequency
    return tfDict

In [27]:
#term frquency for doc1
tfA = computeTF(vectorA, bowDOC1)
#find the term frequencies for doc2 and doc3, store them in variables tfB and tfC
tfB = computeTF(vectorB, bowDOC2)
tfC = computeTF(vectorC, bowDOC3)

In [28]:
tfB

{'soothes': 0.2,
 'is': 0.0,
 'rain': 0.2,
 'When': 0.0,
 'begin': 0.0,
 'winter': 0.0,
 'does': 0.0,
 'long': 0.0,
 'but': 0.0,
 ',': 0.0,
 'summer': 0.0,
 'soul': 0.2,
 'lovely': 0.0,
 'The': 0.2,
 'my': 0.2}

In [29]:
#function for computing inverse document frequency
def computeIDF(documents):
    import math
    N = len(documents)

    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1

    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [30]:
idfs = computeIDF([vectorA, vectorB, vectorC])
idfs

{'soothes': 1.0986122886681098,
 'is': 1.0986122886681098,
 'rain': 1.0986122886681098,
 'When': 1.0986122886681098,
 'begin': 1.0986122886681098,
 'winter': 1.0986122886681098,
 'does': 1.0986122886681098,
 'long': 1.0986122886681098,
 'but': 1.0986122886681098,
 ',': 1.0986122886681098,
 'summer': 1.0986122886681098,
 'soul': 1.0986122886681098,
 'lovely': 1.0986122886681098,
 'The': 0.4054651081081644,
 'my': 1.0986122886681098}

In [31]:
#tfidf is just tf*idf
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [34]:
#find the tfidf for 3 documents and represent them in a data frame
#your code here
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
tfidfC = computeTFIDF(tfC, idfs)
df = pd.DataFrame([tfidfA, tfidfB, tfidfC])
print(df)

    soothes        is      rain      When     begin    winter      does  \
0  0.000000  0.000000  0.000000  0.366204  0.183102  0.000000  0.183102
1  0.219722  0.000000  0.219722  0.000000  0.000000  0.000000  0.000000
2  0.000000  0.183102  0.000000  0.000000  0.000000  0.183102  0.000000

       long       but         ,    summer      soul    lovely       The  \
0  0.000000  0.000000  0.183102  0.183102  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000  0.000000  0.219722  0.000000  0.081093
2  0.183102  0.183102  0.000000  0.000000  0.000000  0.183102  0.067578

         my
0  0.000000
1  0.219722
2  0.000000

In [35]:
df

,soothes,is,rain,When,begin,winter,does,long,but,",",summer,soul,lovely,The,my
0,0.000000,0.000000,0.000000,0.366204,0.183102,0.000000,0.183102,0.000000,0.000000,0.183102,0.183102,0.000000,0.000000,0.000000,0.000000
1,0.219722,0.000000,0.219722,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.219722,0.000000,0.081093,0.219722
2,0.000000,0.183102,0.000000,0.000000,0.000000,0.183102,0.000000,0.183102,0.183102,0.000000,0.000000,0.000000,0.183102,0.067578,0.000000

Now, let's find tfidf using scikit-learn.

In [36]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

#define tfidf vectorizer
vectorizer = TfidfVectorizer()
#fit documents into vectorizer
vectors = vectorizer.fit_transform([doc1, doc2, doc3])
feature_names = vectorizer.get_feature_names_out()
print(feature_names)#prints the vocabulary
#print vectors in a readabke format
dense = vectors.todense()
denselist = dense.tolist()

#print the tfidf vectors
df = pd.DataFrame(denselist, columns=feature_names)
print(df)

['begin' 'but' 'does' 'is' 'long' 'lovely' 'my' 'rain' 'soothes' 'soul'
 'summer' 'the' 'when' 'winter']
      begin       but      does        is      long    lovely        my  \
0  0.377964  0.000000  0.377964  0.000000  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.467351
2  0.000000  0.423394  0.000000  0.423394  0.423394  0.423394  0.000000

       rain   soothes      soul    summer       the      when    winter
0  0.000000  0.000000  0.000000  0.377964  0.000000  0.755929  0.000000
1  0.467351  0.467351  0.467351  0.000000  0.355432  0.000000  0.000000
2  0.000000  0.000000  0.000000  0.000000  0.322002  0.000000  0.423394

The values slightly differ because sklearn uses a slightly different implementation

In [37]:
doc1 = 'Cricket is a bat-and-ball game played between two teams of eleven players'
doc2 = 'The batting side scores runs by striking the ball bowled at the wicket with the bat '
doc3 = 'Means of dismissal include being bowled, when the ball hits the stumps and dislodges the bails'
doc4 = 'Forms of cricket range from Twenty20, with each team batting for a single innings of 20 overs, to Test matches played over five days'

# Split documents into tokens
bowDOC1 = doc1.lower().split()
bowDOC2 = doc2.lower().split()
bowDOC3 = doc3.lower().split()
bowDOC4 = doc4.lower().split()

# Create a new, filtered vocabulary specifically for these documents
cricket_vocab = unique(bowDOC1 + bowDOC2 + bowDOC3 + bowDOC4)
# Filter out general stopwords and special characters
cricket_filtered_vocab = [word for word in cricket_vocab if word not in stopwords and word not in special_char]

# Redefine the vectorize helper for these specific documents
def vectorize_cricket(tokens):
    vector = []
    for w in cricket_filtered_vocab:
        vector.append(tokens.count(w))
    return vector

# Calculate raw bag of words counts
counts1 = vectorize_cricket(bowDOC1)
counts2 = vectorize_cricket(bowDOC2)
counts3 = vectorize_cricket(bowDOC3)
counts4 = vectorize_cricket(bowDOC4)

# Convert the counts list into a dictionary mapped to the cricket vocabulary
vector1 = dict(zip(cricket_filtered_vocab, counts1))
vector2 = dict(zip(cricket_filtered_vocab, counts2))
vector3 = dict(zip(cricket_filtered_vocab, counts3))
vector4 = dict(zip(cricket_filtered_vocab, counts4))

# Compute TF, IDF, and TF-IDF
tfA = computeTF(vector1, bowDOC1)
tfB = computeTF(vector2, bowDOC2)
tfC = computeTF(vector3, bowDOC3)
tfD = computeTF(vector4, bowDOC4)

idfs = computeIDF([vector1, vector2, vector3, vector4])

tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
tfidfC = computeTFIDF(tfC, idfs)
tfidfD = computeTFIDF(tfD, idfs)

df = pd.DataFrame([tfidfA, tfidfB, tfidfC, tfidfD])
print(df)

    matches    wicket      five     means      days    eleven    stumps  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.115525  0.000000
1  0.000000  0.086643  0.000000  0.000000  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.000000  0.086643  0.000000  0.000000  0.086643
3  0.057762  0.000000  0.057762  0.000000  0.057762  0.000000  0.000000

       game     bails      test        at   batting     forms  bat-and-ball  \
0  0.115525  0.000000  0.000000  0.000000  0.000000  0.000000      0.115525
1  0.000000  0.000000  0.000000  0.086643  0.043322  0.000000      0.000000
2  0.000000  0.086643  0.000000  0.000000  0.000000  0.000000      0.000000
3  0.000000  0.000000  0.057762  0.000000  0.028881  0.057762      0.000000

        bat     range      side    overs,   bowled,   cricket   include  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.057762  0.000000
1  0.086643  0.000000  0.086643  0.000000  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.000000  0.000000  0.086643  0.000000  0.086643
3  0.000000  0.057762  0.000000  0.057762  0.000000  0.028881  0.000000

    players    played      hits  dismissal     being      from      team  \
0  0.115525  0.057762  0.000000   0.000000  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.086643   0.086643  0.086643  0.000000  0.000000
3  0.000000  0.028881  0.000000   0.000000  0.000000  0.057762  0.057762

   striking    bowled   between      each        by      with     teams  \
0  0.000000  0.000000  0.115525  0.000000  0.000000  0.000000  0.115525
1  0.086643  0.086643  0.000000  0.000000  0.086643  0.043322  0.000000
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000  0.057762  0.000000  0.028881  0.000000

    innings       and      when       two  dislodges      over  twenty20,  \
0  0.000000  0.000000  0.000000  0.115525   0.000000  0.000000   0.000000
1  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000   0.000000
2  0.000000  0.086643  0.086643  0.000000   0.086643  0.000000   0.000000
3  0.057762  0.000000  0.000000  0.000000   0.000000  0.057762   0.057762

     single       for        20      ball      runs    scores
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000  0.043322  0.086643  0.086643
2  0.000000  0.000000  0.000000  0.043322  0.000000  0.000000
3  0.057762  0.057762  0.057762  0.000000  0.000000  0.000000

# Document Similarity

- Text Similarity has to determine how the two text documents close to each other

- The similarity can be in terms of both context and meaning

- For finding similarity, text needs to be converted into vectors

- There are various text similarity metric exist such as Cosine similarity, Jaccard Similarity.

#Cosine Similarity

- Cosine similarity is a metric used to measure how similar 2 documents are
- Mathematically, it measures the cosine of the angle between two vectors projected in a multi-dimensional space.
- The smaller the angle, higher the cosine similarity.

![Image](https://datascience-enthusiast.com/figures/cosine_sim.png)

In [38]:
doc_1 = "Brazil won the Football world cup five times"
doc_2 = "Italy comes after Brazil in that regard"

#find the bag of word vector representation
CountVec = CountVectorizer(ngram_range=(1,1))
Count_data = CountVec.fit_transform(sentence for sentence in [doc_1, doc_2])
vectorA = Count_data.toarray()[0]
vectorB = Count_data.toarray()[1]

We would now calculate the cosine similarity between documents using Sklearn.

In [39]:
from sklearn.metrics.pairwise import cosine_similarity
#use the cosine_similarity function to calculate cosine distance like this
cosine_similarity_matrix = cosine_similarity(Count_data)
pd.DataFrame(cosine_similarity_matrix,['doc_1','doc_2'])

              0         1
doc_1  1.000000  0.133631
doc_2  0.133631  1.000000

In [46]:
doc_1 = "Sweden is in Scandanavia"
doc_2 = "Denmark is a neighbor of Sweden"
doc_3 = "Norway and Denmark are close by"
#find the pairwise cosine similarity between the documents
#find the bag of word vector representation
CountVec = CountVectorizer(ngram_range=(1,1))
Count_data = CountVec.fit_transform(sentence for sentence in [doc_1, doc_2, doc_3])
vectorA = Count_data.toarray()[0]
vectorB = Count_data.toarray()[1]
vectorC = Count_data.toarray()[2]
#use the cosine_similarity function to calculate cosine distance like this
cosine_similarity_matrix = cosine_similarity(Count_data)
pd.DataFrame(cosine_similarity_matrix,['doc_1','doc_2','doc_3'])

              0         1         2
doc_1  1.000000  0.447214  0.000000
doc_2  0.447214  1.000000  0.182574
doc_3  0.000000  0.182574  1.000000

In [48]:
#your code here
Count_data = CountVec.fit_transform(sentence for sentence in [doc_1, doc_2])
vectorA = Count_data.toarray()[0]
vectorB = Count_data.toarray()[1]
#use the cosine_similarity function to calculate cosine distance like this
cosine_similarity_matrix = cosine_similarity(Count_data)
pd.DataFrame(cosine_similarity_matrix,['doc_1','doc_2'])

              0         1
doc_1  1.000000  0.447214
doc_2  0.447214  1.000000

In [49]:
#your code here
Count_data = CountVec.fit_transform(sentence for sentence in [doc_2, doc_3])
vectorA = Count_data.toarray()[0]
vectorB = Count_data.toarray()[1]
#use the cosine_similarity function to calculate cosine distance like this
cosine_similarity_matrix = cosine_similarity(Count_data)
pd.DataFrame(cosine_similarity_matrix,['doc_2','doc_3'])

              0         1
doc_2  1.000000  0.182574
doc_3  0.182574  1.000000

In [50]:
#your code here
Count_data = CountVec.fit_transform(sentence for sentence in [doc_1, doc_3])
vectorA = Count_data.toarray()[0]
vectorB = Count_data.toarray()[1]
#use the cosine_similarity function to calculate cosine distance like this
cosine_similarity_matrix = cosine_similarity(Count_data)
pd.DataFrame(cosine_similarity_matrix,['doc_1','doc_3'])

         0    1
doc_1  1.0  0.0
doc_3  0.0  1.0

#Jaccard Similarity

- Jaccard Similarity is also known as the Jaccard index and Intersection over Union
- used to determine the similarity between two text document in terms of their context
- similarity is in terms of how many common words are exist over total words

![Image](https://miro.medium.com/max/744/1*XiLRKr_Bo-VdgqVI-SvSQg.png)

More here: https://en.wikipedia.org/wiki/Jaccard_index

In [51]:
# Let's have 2 documents

doc1 = 'A is the brother of B'
doc2 = 'B is the friend of C who is not a brother of A'

In [52]:
#convert documents to lower case - basic preprocessing!
doc1 = doc1.lower()
doc2 = doc2.lower()

In [53]:
#split both the documents into tokens. Make sure that you have no duplicates. You might want to use sets for this purpose!?
#your code here
tokens1=set(doc1.split())
tokens2=set(doc2.split())
print(tokens1)
print(tokens2)

{'the', 'is', 'of', 'a', 'brother', 'b'}
{'the', 'is', 'of', 'a', 'c', 'not', 'who', 'brother', 'b', 'friend'}

In [54]:
#find common words from the 2 documents
#your code here
common=tokens1.intersection(tokens2)
common

{'a', 'b', 'brother', 'is', 'of', 'the'}

In [55]:
#find the vocabulary, total unique words in both documents
#your code here
unique_words=tokens1.union(tokens2)
unique_words

{'a', 'b', 'brother', 'c', 'friend', 'is', 'not', 'of', 'the', 'who'}

In [56]:
#find jaccard similarity
#your code here
jaccard_similarity=len(common)/len(unique_words)
jaccard_similarity

0.6

#Task

Now you are given 4 documents.

- Preprocess them(lowercase, lemmatisation, stop word removal)

- Apply tfidf to convert the sentences into vectors

- Find which of the 4 documents are the most similar to each other


Your 4 sentences are:

1)"Hindi cinema, often known as Bollywood and formerly as Bombay cinema, is the Indian Hindi-language film industry based in Mumbai."

2)"films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before . "

3)"every now and then a movie comes along from a suspect studio , with every indication that it will be a stinker , and to everybody's surprise ( perhaps even the studio ) the film becomes a critical darling . "

4)"The Year 2000 problem, also known as the Y2K problem, the Millennium bug, Y2K bug, the Y2K glitch, or Y2K, refers to events related to the formatting and storage of calendar data for dates beginning in the year 2000"

In [57]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import string

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

# Define the four documents
doc1 = "Hindi cinema, often known as Bollywood and formerly as Bombay cinema, is the Indian Hindi-language film industry based in Mumbai."
doc2 = "films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before . "
doc3 = "every now and then a movie comes along from a suspect studio , with every indication that it will be a stinker , and to everybody's surprise ( perhaps even the studio ) the film becomes a critical darling . "
doc4 = "The Year 2000 problem, also known as the Y2K problem, the Millennium bug, Y2K bug, the Y2K glitch, or Y2K, refers to events related to the formatting and storage of calendar data for dates beginning in the year 2000"

docs = [doc1, doc2, doc3, doc4]

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))
punctuations = set(string.punctuation)

def preprocess(text):
    # Lowercase
    text = text.lower()
    # Tokenize
    tokens = word_tokenize(text)
    # Filter punctuation, stop words, and lemmatize
    cleaned_tokens = [
        lemmatizer.lemmatize(word) for word in tokens
        if word not in stop_words and word not in punctuations and word.isalnum()
    ]
    return " ".join(cleaned_tokens)

# Preprocess all documents
preprocessed_docs = [preprocess(doc) for doc in docs]

# Apply TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(preprocessed_docs)

# Calculate cosine similarity
similarity_matrix = cosine_similarity(tfidf_matrix)

# Create a dataframe for visual comparison
df_similarity = pd.DataFrame(
    similarity_matrix,
    columns=['Doc 1', 'Doc 2', 'Doc 3', 'Doc 4'],
    index=['Doc 1', 'Doc 2', 'Doc 3', 'Doc 4']
)

display(df_similarity)

# Find the most similar pair (excluding self-similarity of 1.0)
max_sim = -1
most_similar_pair = (None, None)

for i in range(len(docs)):
    for j in range(i + 1, len(docs)):
        sim = similarity_matrix[i][j]
        if sim > max_sim:
            max_sim = sim
            most_similar_pair = (i + 1, j + 1)

print(f"\nThe most similar documents are Document {most_similar_pair[0]} and Document {most_similar_pair[1]} with a Cosine Similarity score of {max_sim:.4f}.")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

          Doc 1     Doc 2     Doc 3     Doc 4
Doc 1  1.000000  0.020408  0.023509  0.024844
Doc 2  0.020408  1.000000  0.016521  0.000000
Doc 3  0.023509  0.016521  1.000000  0.000000
Doc 4  0.024844  0.000000  0.000000  1.000000

The most similar documents are Document 1 and Document 4 with a Cosine Similarity score of 0.0248.